const userPermissions = {
    ADMIN: [
        "dashboard",
        "home",
        "logout",
        "forgotPassword",
        "resetPassword",
        "changePassword",
        "user/:id",
        "userList",
        "addUser",
        "getUserList",
        "getUserDetails",
        "updateUserData",
        "deleteUserData",
        "getCountryList",
        "getStateList",
        "getCityList",
        "chat/:chatId/:senderId/:receiverId",
        "profile",
        "friendsList"
    ],
    SUBADMIN: [
        "dashboard",
        "home",
        "logout",
        "userList",
        "getUserList",
        "getCountryList",
        "getStateList",
        "getCityList",
        "profile",
    ],
    USER: [
        "logout",
        "chat/:chatId/:senderId/:receiverId",
        "profile",
        "friendsList"
        // "dashboard",
        // "home",
        // "userList",
        // "getCountryList",
        // "getStateList",
        // "getCityList",
    ],
    MERCHANT: [
        "dashboard",
        "home",
        "logout",
        "userList",
        "getUserList",
        "getCountryList",
        "getStateList",
        "getCityList",
        "profile",
        "chat"
    ],
};

module.exports = { userPermissions };