export const ENDPOINTS = {
    SESSION_DATA: 'sessionData',
    INDEX: 'index',
    LOGIN: 'login',
    LOGIN_ACTION: 'loginAction',
    HOME: 'home',
    LOGOUT: 'logout',
    GENERATE_OTP: 'generateOtp',
    FORGOT_PIN: 'forgotPin',
    LOGIN_OTP: 'loginOtp',
    VERIFY_OTP :"verifyOtp",
    RESET_PASSWORD: 'resetPassword',
    CHANGE_PASSWORD: 'changePassword',
    DASHBOARD: 'dashboard',
    ERROR: 'error',
    OOPS: 'oops',
    USER : 'user',
    USER_LIST: 'userList',
    ADD_USER: 'addUser',
    GET_USER_LIST: 'getUserList',
    GET_USER_DETAILS: 'getUserDetails',
    UPDATE_USER_DATA: 'updateUserData',
    DELETE_USER_DATA: 'deleteUserData',
    GET_COUNTRY_LIST: 'getCountryList',
    GET_STATE_LIST: 'getStateList',
    GET_CITY_LIST: 'getCityList',
    PROFILE: 'profile'
}