export const ENDPOINTS = {
    SESSION_DATA: 'sessionData',
    INDEX: 'index',
    LOGIN: 'login',
    LOGIN_ACTION: 'loginAction',
    HOME: 'home',
    LOGOUT: 'logout',
    GENERATE_OTP_ACTION: 'generateOtpAction',
    FORGOT_PIN: 'forgotPin',
    LOGIN_OTP: 'loginOtp',
    VERIFY_OTP_ACTION :"verifyOtpAction",
    CHANGE_PIN: 'changePin',
    CHANGE_PIN_ACTION: 'changePinAction',
    DASHBOARD: 'dashboard',
    ERROR: 'error',
    OOPS: 'oops',
    USER : 'user',
    USER_LIST: 'userList',
    ADD_USER_ACTION: 'addUserAction',
    GET_USER_LIST_ACTION: 'getUserListAction',
    GET_USER_DETAILS_ACTION: 'getUserDetailsAction',
    UPDATE_USER_ACTION: 'updateUserAction',
    DELETE_USER_ACTION: 'deleteUserAction',
    GET_COUNTRY_LIST: 'getCountryList',
    GET_STATE_LIST: 'getStateList',
    GET_CITY_LIST: 'getCityList',
    PROFILE: 'profile'
}